language: python
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_c3d1330656d5_key -iv $encrypted_c3d1330656d5_iv
  -in deploy_key.enc -out deploy_key -d
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install pytest-cov
script:
- py.test --cov .
- fab deploy -i deploy_key -H $host
after_success:
- coveralls
branches:
  only:
    - master

